# Несколько примеров использования Numpy

1. Письменный экзамен оказался слишком сложным, и преподаватель решил добавить каждому студенту не менее некоторого количества очков, чтобы в итоге было поменьше плохих оценок. Поможем ему пересчитать первичные баллы в итоговые.

Импортируем библиотеку Numpy:

In [4]:
import numpy as np

Зададим среднее значение итоговых баллов:

In [5]:
CURVE_CENTER = 80

Создадим массив оценок:

In [6]:
grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])

Напишем функцию, которая осуществляет пересчёт:

In [7]:
def curve(grades):
    average = grades.mean() # определяем средний первичный балл
    change = CURVE_CENTER - average # определяем количество добавляемое количество очков
    new_grades = grades + change # добавляем это количество очков
    return np.clip(new_grades, grades, 100)

Рассмотрим последнюю строку. Если новая оценка оказалась меньше старой, заменяем её на старую, а если больше 100 - то заменяем на 100. Вызовем функцию:

In [8]:
print(curve(grades))

[ 91.25  54.25  83.25 100.    70.25 100.    93.25  31.25]


## Упражнение 1

В файле `melting.txt` приведены значения флуоресценции различных образцов в диапазоне температур от 28 до 95 градусов. Сами эти абсолютные значения не слишком интересуют исследователей: важнее форма кривых. Чтобы было удобнее сравнивать кривые между собой, отнормируйте их (минимальное значение - 0, максимальное - 1, промежуточное значение делится на разницу между максимальным и минимальным значением). Постройте графики получившихся кривых.

2. Изменение формы массива, многомерные массивы

Массив не обязан иметь форму 1×n, то есть быть просто последовательностью чисел. Можно использовать многомерные массивы. Создадим массив от 1 до 24:

In [9]:
twentyfour = np.arange(1, 25, 1)
twentyfour

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

Создадим на его основе трёхмерный массив:

In [11]:
three_d = twentyfour.reshape(2, 3, 4)
three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

Вычислим среднее значение трёхмерного массива:

In [13]:
three_d.mean()

12.5

Вычислим средние от соответствующих значений первого и второго 2D-массивов, входящих в состав 3D-массива:

In [14]:
three_d.mean(axis=0)

array([[ 7.,  8.,  9., 10.],
       [11., 12., 13., 14.],
       [15., 16., 17., 18.]])

Вычислим средние от каждого столбца 2D-массивов, входящих в состав 3D-массива:

In [15]:
three_d.mean(axis=1)

array([[ 5.,  6.,  7.,  8.],
       [17., 18., 19., 20.]])

Вычислим средние от каждой строки 2D-массивов, входящих в состав 3D-массива:

In [16]:
three_d.mean(axis=2)

array([[ 2.5,  6.5, 10.5],
       [14.5, 18.5, 22.5]])

## Упражнение 2

Прочитайте файлы `ex2_1.txt` и `ex2_2.txt` в двумерный массив, вычислите среднее по каждому столбцу. Читая файлы, исходите из предположения, что количество столбцов в файле заранее неизвестно. Числа в строке разделены табуляцией.

3. Взятие элементов по индексу

Можно создавать массивы-"срезы" на основании имеющихся массивов:

In [18]:
print(three_d[0, ::2,]) # взяли первый 2D-массив из 3D-массива, вытащили нечётные строки полностью

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [21]:
print(three_d[:, 1:, 1:]) # в каждом из 2D-массивов отбросили первую строку и первый столбец

[[[ 6  7  8]
  [10 11 12]]

 [[18 19 20]
  [22 23 24]]]


## Упражнение 3

Задан двумерный массив:

```
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])
```
Вычислите сумму чисел в каждом столбце, в каждой строке, в каждом квадрате 2×2, который можно вырезать из имеющегося (5 шт). Выведите её на экран для каждого случая.

4. Фильтрация массива

В некоторых случаях требуется выбрать элементы не по индексу, а по какому-то признаку, например, делимость на 3. Для этого можно создать массив-маску. Он имеет ту же форму, что и исходный массив, однако содержит булевские значения (`True`/`False`)

Создадим случайный массив 4×3 и получим маску по условию "делится на 3":

In [24]:
rnd_array = np.random.randint(0, 21, size=(4, 3))
print(rnd_array)

mask = rnd_array % 3 == 0
print(mask)

[[ 1  4 19]
 [14 11  4]
 [ 4 15  5]
 [10  7  4]]
[[False False False]
 [False False False]
 [False  True False]
 [False False False]]


In [25]:
rnd_array[mask]

array([15])

## Упражнение 4

Вычислите среднее и стандартное отклонение чисел из файла `ex4.txt`, затем найдите выбросы (*x* < *Q*1 - 1.5 × *IQR* или *x* > *Q*3 + 1.5 × *IQR*  и вычислите среднее и стандартное отклонение без них.